language: cpp

compiler:
  - gcc
  - clang

install: sudo pip install cpp-coveralls
script: EXTRA_CFLAGS="--coverage" EXTRA_LDFLAGS="-coverage" make tool test -j4
after_success:
  - ./sourcemap -v
  - ./sourcemap --help
  - ./sourcemap -t < test/output.js.map
  - ./sourcemap -d < test/output.js.map > /dev/null
  - coveralls --exclude json.cpp --exclude json.hpp --exclude UnitTest++ --gcov-options '\-lp'

